### PR TITLE
Update : Updated UI 

### PR DESCRIPTION
**Pull request by Akshit-Nandan**
Solved #7
Following changes were performed
- Updated Linear Layout to Constraint Layout
- Changed color button, text, background 
- Made button round
<tr>
<td>
Before

</td>
<td>
After

</td>
</tr>

### CODE REVIEW

**Comment by Smarshal21** [comment]
@Akshit-Nandan could you please change that background colour to something more suitable
?

**Comment by LCB2021029-Badri** [comment]
its hard to read with the above colour combination.
try to make the text more readable @Akshit-Nandan

**Comment by Akshit-Nandan** [comment]
> 

Ok sir

**Comment by Akshit-Nandan** [comment]
> its hard to read with the above colour combination. try to make the text more readable @Akshit-Nandan

Sir updated

**Pull request closed without merging**
